CONTRIBUTING.md, Makefile, build/package/release.sh, doc/release.md
=> Tweak release scripts and polish the release doc

build/images/Dockerfile.release
=> Add Dockerfile for release

build/images/Dockerfile.release
Fix https://github.com/apache/skywalking/issues/6042.
Once merged, I will push and override images at docker hub.
=> Place the manager binary in the right path

config/adapter/namespaced/adapter/kustomization.yaml, config/operator/manager/kustomization.yaml
=> Update image tag to 0.2.0

Makefile, build/images/Dockerfile.adapter, build/images/Dockerfile.release, build/package/release.sh, config/adapter/namespaced/adapter/adapter.yaml
Update release related scripts for releasing HPA adapter.
=> Update release scripts

config/adapter/namespaced/adapter/kustomization.yaml, config/operator/manager/kustomization.yaml
These changes aim to release 0.3.0
=> Release 0.3.0

NOTICE, dist/NOTICE
=> Update NOTICE year to 2021

docs/release.md
Add an operation to remove old tarballs after pushing the new one.
=> Update release document

.github/workflows/go.yml, Makefile, test/e2e/demo.yaml, test/e2e/deploy-elasticsearch.yaml, test/e2e/external-storage.yaml, test/e2e/internal-storage.yaml, test/e2e/oap-ui-agent-external-storage/e2e.yaml, test/e2e/oap-ui-agent-internal-storage/e2e.yaml, test/e2e/oap-ui-agent/e2e.yaml, test/e2e/oapserver-cases.yaml, test/e2e/skywalking-components-with-storage.yaml, test/e2e/ui-cases.yaml, test/e2e/verify/indices.yaml
The PR is to add e2e test about `oap+ui+agent+internel/external storage`.
=> add e2e-test(oap+ui+internel/external storage)

.github/workflows/go.yml, Makefile, config/adapter/namespaced/apiservice/external.yaml, config/dev/adapter/adapter.yaml, docs/custom-metrics-adapter.md, test/e2e/demo.yaml, test/e2e/hpa-demo.yaml, test/e2e/oap-agent-adapter-hpa/e2e.yaml, test/e2e/oap-ui-agent-external-storage/e2e.yaml, test/e2e/oap-ui-agent-internal-storage/e2e.yaml, test/e2e/verify/hpa-metrics.yaml, test/e2e/verify/replicas.yaml
The PR is to add adapter e2e, which means the pod's replicas can be autoscaled according to the data of oap.
=> add adapter e2e

build/images/Dockerfile.release, build/images/Dockerfile.release-bin
Signed-off-by: Hongtao Gao <hanahmily@gmail.com>
=> Update release images to set numeric user id

operator/pkg/operator/manifests/satellite/templates/deployment.yaml, operator/pkg/operator/repo/assets.gen.go
When I tried to set the config in the Satellite component, and the config value is a number, then the satellite could not set up.
=> Fix the satellite config not support number error

CHANGES.md, docs/examples/java-agent-injector-usage.md, docs/java-agent-injector.md, operator/pkg/operator/manifests/injector/templates/annotations.yaml, operator/pkg/operator/repo/assets.gen.go, test/e2e/demo.yaml
Signed-off-by: dashanji <952129620@qq.com>
=> use JAVA_TOOL_OPTIONS to replace AGENT_OPTS

CHANGES.md, adapter/config/namespaced/adapter/adapter.yaml
Resolve https://github.com/apache/skywalking/issues/8437
=> Fix could not deploy metrics adapter to GKE

hack/prepare-e2e.sh
Signed-off-by: dashanji <952129620@qq.com>
=> [BUG]fix shell assignment

docs/java-agent-injector.md, operator/config/samples/default.yaml, operator/pkg/operator/injector/injector.go, operator/pkg/operator/injector/validate.go, operator/pkg/operator/manifests/injector/templates/annotations.yaml, operator/pkg/operator/repo/assets.gen.go, test/e2e/demo.yaml
The PR is related to https://github.com/apache/skywalking/issues/8258.
=> add resource limits and requests

README.md, docs/operator.md
We received some feedback about how to deploy a released operator. I add relevant details to the documents in these changes.
=> Add more details about how to deploy the operator based on a released package

CHANGES.md, adapter/config/namespaced/adapter/kustomization.yaml, docs/java-agent-injector.md, operator/apis/operator/v1alpha1/swagent_types.go, operator/config/manager/kustomization.yaml, operator/config/samples/swagent.yaml
* Update `changed.md`.
* Update image tags of adapter and operator.
Signed-off-by: Ye Cao <dashanjic@gmail.com>
=> Preparation of release 0.7.0

docs/release.md
Signed-off-by: Ye Cao <dashanjic@gmail.com>
=> Improve the release doc

CHANGES.md, operator/pkg/operator/injector/injector.go, test/e2e/oap-ui-agent/e2e.yaml
As titled. Fix https://github.com/apache/skywalking/discussions/11191
=> Avoid duplicated injection while injecting java agent.

.github/workflows/go.yml, CHANGES.md, adapter/Dockerfile, adapter/dist/LICENSE, adapter/go.mod, adapter/go.sum, hack/build/module.mk, operator/Dockerfile, operator/dist/LICENSE, operator/go.mod, operator/go.sum
Fix the following security issues:
- https://github.com/apache/skywalking-swck/security/dependabot/27
- https://github.com/apache/skywalking-swck/security/dependabot/28
- https://github.com/apache/skywalking-swck/security/dependabot/29
=> Bump up golang to v1.22 and fix security issues.

docs/examples/event-exporter.md, docs/menu.yml
Add doc explaining how to use the EventExporter CRD added in #113.
=> Add doc for EventExporter
